name = "ExamplePackage"
uuid = "b29df0d8-8d56-11e9-2988-8786d2bf7345"
authors = ["Kaj Wiik <kjwiik@iki.fi>"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
